//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleNameRetagger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapleNameRetagger.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}
        ///{1}.
        /// </summary>
        internal static string ErrorException {
            get {
                return ResourceManager.GetString("ErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: File load failure or empty document..
        /// </summary>
        internal static string ErrorFileLoadErrorOrFileEmpty {
            get {
                return ResourceManager.GetString("ErrorFileLoadErrorOrFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: No target file supplied and default file (.\{0}) not found. Process Terminates..
        /// </summary>
        internal static string ErrorTargetOrSuppliedFileNotFound {
            get {
                return ResourceManager.GetString("ErrorTargetOrSuppliedFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: [{0}] =&gt; Applied edit to canvas..
        /// </summary>
        internal static string InfoAppliedCanvas {
            get {
                return ResourceManager.GetString("InfoAppliedCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: [{0}] =&gt; Applied edit to image and canvas..
        /// </summary>
        internal static string InfoAppliedImageAndCanvas {
            get {
                return ResourceManager.GetString("InfoAppliedImageAndCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Finished processing, attempting to save!.
        /// </summary>
        internal static string InfoFinishedProcessingAttemptingToSave {
            get {
                return ResourceManager.GetString("InfoFinishedProcessingAttemptingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Saved successfully!.
        /// </summary>
        internal static string InfoSavedSuccessfully {
            get {
                return ResourceManager.GetString("InfoSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARN: [{0}] e.height property is less than real image height, skipping!.
        /// </summary>
        internal static string WarnHeightLessThanReal {
            get {
                return ResourceManager.GetString("WarnHeightLessThanReal", resourceCulture);
            }
        }
    }
}
